/* logico: */

CREATE TABLE EMPRESA (
    id INTEGER PRIMARY KEY,
    nome VARCHAR,
    cnpj VARCHAR,
    tipo VARCHAR
);

CREATE TABLE USUARIO (
    id INTEGER PRIMARY KEY,
    nome VARCHAR,
    telefone VARCHAR,
    email VARCHAR,
    senha VARCHAR,
    tipo INTEGER,
    status INTEGER,
    created DATETIME,
    last_access DATETIME
);

CREATE TABLE PROJETO (
    id INTEGER PRIMARY KEY,
    viabilidade VARCHAR,
    efeitos VARCHAR,
    equipe VARCHAR,
    nome VARCHAR,
    riscos VARCHAR,
    entregas VARCHAR,
    premissas VARCHAR,
    cronograma VARCHAR,
    custo VARCHAR,
    anotacoes_complementares VARCHAR,
    interessados VARCHAR,
    finalizado INTEGER,
    created DATETIME,
    modified DATETIME,
    FK_EMPRESA_id INTEGER,
    FK_USUARIO_id INTEGER
);

CREATE TABLE PRODUTO (
    id INTEGER PRIMARY KEY,
    descricao VARCHAR,
    nome VARCHAR,
    FK_PROJETO_id INTEGER
);
 
ALTER TABLE PROJETO ADD CONSTRAINT FK_PROJETO_2
    FOREIGN KEY (FK_EMPRESA_id)
    REFERENCES EMPRESA (id)
    ON DELETE RESTRICT;
 
ALTER TABLE PROJETO ADD CONSTRAINT FK_PROJETO_3
    FOREIGN KEY (FK_USUARIO_id)
    REFERENCES USUARIO (id)
    ON DELETE RESTRICT;
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_2
    FOREIGN KEY (FK_PROJETO_id)
    REFERENCES PROJETO (id)
    ON DELETE RESTRICT;